// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-ZkFyUvb7Zo32bnJmiLpuziRfXXs9WQ',
    appId: '1:242025003686:web:976a4cc9ea2e5339ca9267',
    messagingSenderId: '242025003686',
    projectId: 'kongsi-3cadd',
    authDomain: 'kongsi-3cadd.firebaseapp.com',
    storageBucket: 'kongsi-3cadd.firebasestorage.app',
    measurementId: 'G-823BGM91FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADI2VzaCvXeV9kcOR_cgn8WDjgM973Exc',
    appId: '1:242025003686:android:6a35f95943468262ca9267',
    messagingSenderId: '242025003686',
    projectId: 'kongsi-3cadd',
    storageBucket: 'kongsi-3cadd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kKEQj6IFhvwBcQ50CjMRiC_esLHWgxk',
    appId: '1:242025003686:ios:7c69368dff8a99c2ca9267',
    messagingSenderId: '242025003686',
    projectId: 'kongsi-3cadd',
    storageBucket: 'kongsi-3cadd.firebasestorage.app',
    iosClientId: '242025003686-d3j356886e5fmblvkdtsrpbiasfs6332.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectKongsi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kKEQj6IFhvwBcQ50CjMRiC_esLHWgxk',
    appId: '1:242025003686:ios:7c69368dff8a99c2ca9267',
    messagingSenderId: '242025003686',
    projectId: 'kongsi-3cadd',
    storageBucket: 'kongsi-3cadd.firebasestorage.app',
    iosClientId: '242025003686-d3j356886e5fmblvkdtsrpbiasfs6332.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectKongsi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO-ZkFyUvb7Zo32bnJmiLpuziRfXXs9WQ',
    appId: '1:242025003686:web:f75ec23f64407937ca9267',
    messagingSenderId: '242025003686',
    projectId: 'kongsi-3cadd',
    authDomain: 'kongsi-3cadd.firebaseapp.com',
    storageBucket: 'kongsi-3cadd.firebasestorage.app',
    measurementId: 'G-W2MG0Q2LYP',
  );
}
